# This file is part of the Ocrend Framewok 2 package.
#
# (c) Ocrend Software <info@ocrend.com>
#
# For the full copyright and license information, please view the LICENS
# file that was distributed with this source code.

# Conexión con la base de datos principal
database:
  host: localhost
  user: root
  pass:
  name: guarderia
  port: 1521
  protocol: TCP
  motor: mysql

# Configuración de servidor SMTP
phpmailer:
  host:
  user:
  pass:
  port: 465

# Configuración de sesiones
sessions:
  unique: 0CR3ND2017
  life_time: 3600

# Variables del framework
framework:
  debug: true
  version: 2.0.4

# Configuración del sitio
site:
  name: Guarderia
  author: Ramon García, Fernando Gomes y Alexander De Azevedo
  author_email: oeneikaphotos@gmail.com
  timezone: America/Caracas
  url: http://localhost/guarderia/Sistema/
  router:
    path: localhost/guarderia/Sistema/
    protocol: http
